general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = pidof hyprlock || hyprlock
    after_sleep_cmd = hyprctl dispatch dpms on
    inhibit_sleep = 3
    on_unlock_cmd = sh -c 'pkill -x hypridle; (hypridle &); ~/.config/hypr/restart-quickshell.sh'
}

# 🔒 Bloqueia a tela após 10 minutos
listener {
    timeout = 600
    on-timeout = pidof hyprlock || hyprlock
}

# 🌙 Desliga o monitor após 15 minutos (DPMS off)
listener {
    timeout = 900
    on-timeout = hyprctl dispatch dpms off
    # on-resume pode ficar, mas não dependa dele
    on-resume = sh -c 'hyprctl dispatch dpms on; ~/.config/hypr/restart-quickshell.sh'
}

# 🛎️ Aviso 1 min antes de suspender
listener {
    timeout = 1140
    on-timeout = notify-send "Hyprland" "⚠️ The system will be suspended in 1 minute.." --urgency=critical
}

# 💤 Suspende após 20 minutos
listener {
    timeout = 1200
    on-timeout = systemctl suspend-then-hibernate
}
